#!/bin/sh

set -e

aclocal
automake --add-missing
autoconf

echo "#     libOpenACC" ; cd libOpenACC ; ./build ; cd ..
echo "#     rose"       ; cd rose       ; ./build ; cd ..
echo "#     RoseACC"    ; cd RoseACC    ; ./build ; cd ..
echo "#     tests"      ; cd tests      ; ./build ; cd ..

